##
# Subistitui banco de testes
##
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=carros_test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES


# Habilita log do Contexto transacional
logger:
  levels:
    io.micronaut.transaction: DEBUG

jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update